// <auto-generated />
namespace RMMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userinfo_userrequest_coledit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userinfo_userrequest_coledit));
        
        string IMigrationMetadata.Id
        {
            get { return "201908080313565_userinfo_userrequest_col-edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
