// <auto-generated />
namespace RMMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class remove_statusCol_UserRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(remove_statusCol_UserRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201908100126042_remove_statusCol_UserRequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
