// <auto-generated />
namespace RMMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_SortedBalanceDetail_UnsortedBalanceDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_SortedBalanceDetail_UnsortedBalanceDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201908110003003_create_SortedBalanceDetail_UnsortedBalanceDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
