// <auto-generated />
namespace RMMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_Admin_Employee_customer_RiceType_ExtraType_ExtraBalanceDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_Admin_Employee_customer_RiceType_ExtraType_ExtraBalanceDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "201908102329425_Create_Admin_Employee_customer_RiceType_ExtraType_ExtraBalanceDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
