// <auto-generated />
namespace RMMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Userinfo_col_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Userinfo_col_add));
        
        string IMigrationMetadata.Id
        {
            get { return "201908051920492_Userinfo_col_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
