// <auto-generated />
namespace RMMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userinfo_usercodeType_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userinfo_usercodeType_change));
        
        string IMigrationMetadata.Id
        {
            get { return "201908080317335_userinfo_usercodeType_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
